### ISSUE TITLE
Parse failure

### ISSUE THREAD

**Issue by buggymcbugfix** [mitsuji/mssql-simple#2]
Hi, thanks for providing this library :)

What am I doing wrong if I'm getting
```
mssql-simple: user error (sql: failed to parse token streams)
```
? The query I'm running is a `SELECT` on tables.

**Comment by buggymcbugfix** [comment]
I can provide more details by email if necessary.

**Comment by mitsuji** [comment]
Hi, thank you for contacting.

It seems to failed to parse the ResultSet.
Class instance of ResultSet are (), RowCount, ReturnStatus and ((Row a) => ResultSet [a]).
The data type specified in Haskell code must match the one that can be acquired by the SQL statement.
http://hackage.haskell.org/package/mssql-simple-0.6.0.0/docs/Database-MSSQLServer-Query.html#g:1

But it could be a library bug.
That in case SQL Server responded in a way that we don't expect yet.

If you give me the details, I might be able to solve it.
Please tell me below by email if you don't mind.

* SQL Server Version 
* SQL Server Compatibility Level
* SELECT Statement
* CREATE TABLE Statement (I'm interested in data types of rows)
* Related Haskell Code
* Stack lts version or GHC version

I'm a weekend programmer on this subject, so please forgive me even if my response is late.

**Comment by buggymcbugfix** [comment]
I can't look into this now, but I'll reopen if it happens again. Thank you for your efforts!

**Comment by DivyaNesana** [comment]
I have a similar issue and I'm getting the error **"user error (sql: failed to parse token streams)"**
I'm using the **sql** function to execute insert queries in database.
I have **two insert queries** and both of them are failing because of **Foreign key constraint** but the error/exception is not giving me useful information.

sql connection "INSERT INTO Table(Col1, Col2) VALUES (Val1,  Val2); INSERT INTO Table(Col1, Col2) VALUES (Val1, Val2);"

If one insert failed then I'm getting the proper error from QueryError but if more than one error then I think the error is not parsed successfully.
